server:
  port: 8080
spring:
  application:
    name: kudos
  datasource:
    url: jdbc:mysql://39.103.66.26:3306/db_order_pay?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Suz1@mysql
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      max-poll-records: 100
      max-partition-fetch-bytes: 1000000

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, env, metrics